on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: curl -X POST https://webteam-ircbot.canonical.com/hubot/canonicool-reminders-check
